import { DEMO_AUDIT_RECORDS, DEMO_GAME_NAME } from "@/lib/seed";
import { PageHeader } from "@/components/PageHeader";
import { GovernanceAuditTable } from "@/components/GovernanceAuditTable";
import { LedgerIntegrityCard } from "@/components/LedgerIntegrityCard";

export const metadata = { title: "Governance Audit — Greenlight" };

export default function ActivityPage() {
  const records = DEMO_AUDIT_RECORDS;

  const deployed = records.filter((r) => !!r.deploymentId).length;
  const sealedToLedger = records.filter((r) => !!r.ledgerItemId).length;
  const withOutcome = records.filter((r) => r.outcomeStatus && r.outcomeStatus !== "pending").length;

  return (
    <div className="space-y-8">
      <PageHeader
        title="Governance Audit"
        subtitle={`${DEMO_GAME_NAME} · Complete accountability record — exportable as PDF`}
      />

      {/* Summary stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { label: "Total decisions", value: records.length },
          { label: "Deployed",        value: deployed },
          { label: "Sealed to Ledger",value: sealedToLedger },
          { label: "Outcomes measured",value: withOutcome },
        ].map(({ label, value }) => (
          <div key={label} className="gl-card text-center">
            <p className="text-2xl font-bold text-zinc-100">{value}</p>
            <p className="text-xs text-zinc-500 mt-0.5">{label}</p>
          </div>
        ))}
      </div>

      {/* Ledger integrity model — answer "is this just a database?" */}
      <LedgerIntegrityCard />

      {/* The audit table */}
      <GovernanceAuditTable records={records} />

      {/* Print footer (only visible when printing) */}
      <div className="print-only mt-8 pt-4 border-t border-zinc-300 text-xs text-zinc-500">
        <p>Greenlight Governance Audit Export · {DEMO_GAME_NAME}</p>
        <p>Generated: {new Date().toLocaleString()}</p>
        <p>This document was generated by Greenlight — governed live ops. All records are sealed to the Project0 Core Ledger and tamper-evident.</p>
      </div>
    </div>
  );
}
